#Demo build
name: CI/CD Demo
on:
  [pull_request, push]
jobs:
  build:
    runs-on: Linux

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - name: Build with VSCE
        run: npm run build
      - name: Publish to Nexus
        run: |
          echo "$(find . -name "*.vsix")"
          echo "$(basename `$(find . -name "*.vsix")`"
